[package]
name = "strahl"
version = "0.1.0"
authors = ["Fabian Wahlster <wahlster@ux3d.io>"]
edition = "2018"

[dependencies]
packed_simd = { version="*", features=["into_bits"]}
rayon = "*"
image = "*"
rand = "*"

